### ISSUE TITLE
Features missing from 2.0.0

### ISSUE THREAD

**Issue by jeremymv2** [chef-cookbooks/audit#116]
### Cookbook version
2.0.0

### Chef-client version
any

### Platform Details
any

### Info:
These capabilities are removed from 2.0.0.  What is the consensus on re-adding them?
- [x] upload profiles to Compliance server
- [ ] report via Chef Server #129 
- [x] report to Compliance Server
- [x] interval reports

**Comment by vjeffrey** [comment]
in the process! wanted to name that 2.0.0-beta, but the linting/rubocop didn't like that.  I'm working on the compliance parts right now, and then chef server is next

**Comment by vjeffrey** [comment]
profile upload: https://github.com/chef-cookbooks/audit/pull/122

**Comment by vjeffrey** [comment]
integrate with compliance wip: https://github.com/chef-cookbooks/audit/compare/vj/integrate-with-compliance

**Comment by chris-rock** [comment]
I close this issue now, the missing Chef Server authentication is tracked in #129
