### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by chris-rock** [chef-cookbooks/audit#128]
https://github.com/chef-cookbooks/audit/pull/122 re-added support for compliance profile upload. This PR has not covered the unit tests and we should add enable them for 2.0 release.

**Comment by jeremymv2** [comment]
This is what the previous upload unit tests looked like: https://github.com/jeremymv2/audit/blob/7c1930a46dcda3aa0b16e0ae2749d8b3f9a5edd5/spec/unit/recipes/upload_spec.rb

**Comment by chris-rock** [comment]
This should clean up all unit tests:
- for profile upload

We should have a separate file for component and visibility should move from helpers as well.
