### ISSUE TITLE
Support certificates (insecure) for reporting to chef-visibility

### ISSUE THREAD

**Issue by vjeffrey** [chef-cookbooks/audit#150]
### Cookbook version
2.0

```
ERROR: SSL Validation failure connecting to host: lprsedifcha001v.int.asurion.com - SSL_connect returned=1 errno=0 state=error: certificate verify failed
ERROR: send_inspec_report: POSTing to https://lprsedifcha001v.int.asurion.com/data-collector/v0/ returned: SSL Error connecting to https://lprsedifcha001v.int.asurion.com/data-collector/v0/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

need to add insecure option for visibility

**Comment by vjeffrey** [comment]
" But we should document that SSL certs can/should be placed in `/etc/chef/trusted_certs`

*when using visibility"  <-- from @jerryaldrichiii

**Comment by jerryaldrichiii** [comment]
@chris-rock submitted PR #152 which handles this well @vjeffrey

**Comment by chris-rock** [comment]
We may should still allow users to enable `insecure` here: https://github.com/chef-cookbooks/audit/blob/1ea498bb9ed6fcdf85299b3478273b375d676a49/libraries/collector_classes.rb#L54 as we do for chef-server https://github.com/chef-cookbooks/audit/blob/1ea498bb9ed6fcdf85299b3478273b375d676a49/libraries/collector_classes.rb#L276-L277

**Comment by jerryaldrichiii** [comment]
Here is an attempt ^

Needs testing/vetting though. Let me know if I can help.
