### ISSUE TITLE
fail_if_not_present doesn't work

### ISSUE THREAD

**Issue by omgroves** [chef-cookbooks/audit#166]
### Cookbook version
2.1.0

### Chef-client version
12.9

### Platform Details
CentOS 7.2, Chef Server 12

### Scenario:
If the compliance profile does not exist and the attribute ['audit']['fail_if_not_present'] is TRUE, the cookbook should failed to converge. This does not happen. Everything converges as normal, but no compliance profiles are run.

### Steps to Reproduce:
Run audit cookbook with fail_if_not_present set to true and a non-existent compliance profile in ['audit']['profiles']

### Expected Result:
Should fail to converge

### Actual Result:
Does not fail to converge

**Comment by chris-rock** [comment]
@omgroves Thank you for reporting that issue
