### ISSUE TITLE
Unable to use GIT as a profile source

### ISSUE THREAD

**Issue by username-is-already-taken2** [chef-cookbooks/audit#172]
### Cookbook version
0.2.3

### Chef-client version
12.16.42

### Platform Details
chef-client running on windows 2012 R2

### Scenario:
Using the same node I am able to use the audit cookbook and call compliance profiles hosted on the chef-compliance server but I am getting an error when trying to run the profiles directly from git

### Steps to Reproduce:
Same cookbook I am changing enviroment attributes to reference my git repo
```
{
  "audit": {
    "collector": "chef-server",
    "insecure": false,
    "profiles": [
      {
        "name": "compliance_constitution",
        "git": "https://git.*********.com/***/compliance_constitution.git"
      }
    ]
  }
}
```

### Expected Result:
Should run my profile, I can run the profile successfully using inspec exec and the http://url to the same repo

### Actual Result:
chef-client run failes 

```[2016-12-01T15:40:45+00:00] ERROR: Report handler Chef::Handler::AuditReport raised #<RuntimeError: Unable to resolve master to a specific git commit for https://git.*********.com/***/compliance_constitution.git>

**Comment by chris-rock** [comment]
@username-is-already-taken2 Is git installed on that machine?

**Comment by username-is-already-taken2** [comment]
No this server doesn't, I'll install it and give it ago.

I did try looking around the code to see how the git intergration works, but with my random clicking of files in the repo I wasn't able to determine that.  

I was just thinking I might be able to raise a PR to fail with a better error if git was not found?  Just thinking.

Anyway thanks for your help

**Comment by chris-rock** [comment]
@username-is-already-taken2 The git fetcher is implemented here https://github.com/chef/inspec/blob/master/lib/fetchers/git.rb#L149 It should output an appropriate error, but if you do not see it from the very beginning, we need to improve that.
