### ISSUE TITLE
json-file, unable to save file on a windows system

### ISSUE THREAD

**Issue by username-is-already-taken2** [chef-cookbooks/audit#173]
### Cookbook version
2.3.0

### Chef-client version
12.16.2

### Platform Details
Windows 2012 R2

### Scenario:
Trying to save the compliance report to disk using the json-file collector

### Steps to Reproduce:
```
{
  "audit": {
    "collector": [
      "chef-server",
      "json-file"
    ],....
```

### Expected Result:
should write the file

### Actual Result:
Client run errors and no file is written to disk
```
[2016-12-02T12:07:44+00:00] WARN: Writing report to file.
[2016-12-02T12:07:44+00:00] WARN: Filename is c:/chef/cache/cookbooks/audit/inspec-2016-12-02_12:07:44_UTC.json
[2016-12-02T12:07:44+00:00] ERROR: Report handler Chef::Handler::AuditReport raised #<Errno::EINVAL: Invalid argument @rb_sysopen - c:/chef/cache/cookbooks/audit/inspec-2016-12-02_12:07:44_UTC.json>
```

**Comment by chris-rock** [comment]
@username-is-already-taken2 Great finding. A colon is an invalid character for a windows file name. We need to change the way the filename is generated

**Comment by jeremymv2** [comment]
I propose we use `Time.now.strftime('%Y%m%d%H%M%S')` instead of `Time.now.utc.to_s.tr(' ', '_')`

Here: https://github.com/chef-cookbooks/audit/blob/5628f4ec5883fb35c5f42111b7c071f5c3ae6f01/spec/unit/libraries/json_file_spec.rb#L12

This will result in a more sort friendly file name, for example:
```
irb(main):022:0> "inspec-#{Time.now.strftime('%Y%m%d%H%M%S')}.json"
=> "inspec-20161202222307.json"
irb(main):023:0>
```

**Comment by chris-rock** [comment]
#177 fixed that issue. @username-is-already-taken2 let us know if the issue continues to persist
