### ISSUE TITLE
Run Chef Automate integration tests in travis

### ISSUE THREAD

**Issue by chris-rock** [chef-cookbooks/audit#178]
### Cookbook version

2.x

### Scenario:

With #175 we are able to run complete integration tests with Chef Automate. At this point we have to run them manually.

### Expected Result:

With every pull request, we want to run the integration tests to ensure we do not break production environments. We could trigger an EC2 run from travis.

**Comment by alexpop** [comment]
Fixed via https://github.com/chef-cookbooks/audit/pull/181
