### ISSUE TITLE
Missing default attribute `fail_if_any_audits_failed`

### ISSUE THREAD

**Issue by seththoenen** [chef-cookbooks/audit#182]
### Cookbook version
2.3.2

### Chef-client version
12.16.42

### Platform Details
Windows Server 2012 R2

### Scenario:
I recently updated my audit cookbook from 0.14.4 to 2.3.2 and it seems the `fail_if_any_audits_failed` attribute is currently missing.

**Comment by cheeseplus** [comment]
We removed all the code that used this so using a current version should work even with this particular bit of code removed.
