### ISSUE TITLE
Document new `chef-server-compliance` collector in Readme

### ISSUE THREAD

**Issue by chris-rock** [chef-cookbooks/audit#190]

**Comment by jerrylws** [comment]
Hi Chris, the collector type "chef-server" seems to be no longer valid?
If that's true, this configuration part in the readme file could be misleading.

"audit": {
  "collector": "chef-server",
  "inspec_version": "1.2.1",
  "profiles": [
    # profile from Chef Compliance
    {
      "name": "linux",
      "compliance": "base/linux"
    },
......

Prolly, it's defined here in the attributes -

# controls where inspec scan reports are sent
# possible values: 'chef-server-visibility', 'chef-server-compliance', 'chef-compliance', 'chef-visibility', 'json-file'
# notes: 'chef-visibility' requires inspec version 0.27.1 or greater
default['audit']['collector'] = 'chef-server-compliance'

**Comment by jerrylws** [comment]
Sorry about the big fonts above for the comments... not sure how they got there.

**Comment by spuder** [comment]
+1

jerrylws the markdown interpreter is converting `#` to large type. Wrap everything in [code fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/f)

**Comment by chris-rock** [comment]
@jerrylws It should still work, we have a fallback implemented. See https://github.com/chef-cookbooks/audit/blob/master/files/default/handler/audit_report.rb#L27-L30

**Comment by jerrylws** [comment]
Thanks Chris.
That also works by taking the default value of the collector.
Profiles have been defined like below in attributes.

default['audit']['profiles'] = 
[
    # profile from Chef Compliance
    {
      "name" => "linux",
      "compliance" => "base/linux"
    },
    {
      "name" => "ssh",
      "compliance" => "base/ssh"
    }              
]

**Comment by chris-rock** [comment]
That is documented in https://github.com/chef-cookbooks/audit#reporting-to-chef-compliance-via-chef-server now
