### ISSUE TITLE
could not find valid gem 'inspec'

### ISSUE THREAD

**Issue by kmanohar1** [chef-cookbooks/audit#194]
My node does NOT have internet connection. I get his error while running chef-client.

STDERR: ERROR:  Could not find a valid gem 'inspec' (= 1.8.0), here is why:
            Unable to download data from https://rubygems.org/ - Errno::EHOSTUNREACH: Failed to open TCP connection to api.rubygems.org:443 (No route to host - connect(2) for "api.rubygems.org" port 443) (https://api.rubygems.org/specs.4.8.gz)

**Comment by vjeffrey** [comment]
hi @kmanohar1; sorry to hear that :(  We've played around with a couple ideas for solving the issue of getting the inspec gem in airgapped environments (https://github.com/chef-cookbooks/audit/issues/112, https://github.com/chef-cookbooks/audit/pull/165) 

If you have an internal gem repo, you could use this functionality: https://github.com/chef-cookbooks/audit/blob/master/attributes/default.rb#L25

curious: what would best solve your needs, of the options above or other?

**Comment by kmanohar1** [comment]
Thank you so much. Overriding 'inspec_gem_source' attribute worked for me.
