### ISSUE TITLE
Direct reporting to Chef Visibility doesn't work when proxying node data through Chef Server

### ISSUE THREAD

**Issue by OBrienCommaJosh** [chef-cookbooks/audit#195]
### Cookbook version
2.3.4

### Chef-client version
12.18.31-1

### Platform Details
Platform-agnostic issue

### Scenario:
When proxying data to Chef Automate via Chef Server, using the default `client.rb` configuration, because there is no `data_collector.server_url` or `data_collector.token` in the `client.rb`, data cannot be sent from the audit cookbook to Chef Automate.

There is a possible workaround by sending data straight from nodes to the Chef Automate server, but that requires opening every node to the Automate Server.

### Steps to Reproduce: 
Prerequisite: Chef Server configured to send node data to Chef Automate.

1. Bootstrap node to Chef Server with audit cookbook in run-list
1. Leave default `client.rb`
1. Confirm that node data is visible in Chef Automate
1. Configure [direct reporting to Chef Visibility](https://github.com/chef-cookbooks/audit#direct-reporting-to-chef-visibility) as described in the audit cookbook readme
1. Receive error that `data_collector.server_url` and `data_collector.token` are not configured in `client.rb`

### Expected Result:
In this situation, the audit cookbook should send data directly to Chef Server in order to be proxied to Chef Automate.

### Actual Result:
Receive error that `data_collector.server_url` and `data_collector.token` are not configured in `client.rb`

cc: @thomascate for additional context

**Comment by thomascate** [comment]
Coming back to this a day later I figured out we should have been using
"Reporting to Chef Automate (Chef Visibility via Chef Server)" from the docs, not direct reporting.
