### ISSUE TITLE
JSON output contains "You have X number of issues or packages out of date"

### ISSUE THREAD

**Issue by ffpollock** [chef-cookbooks/audit#207]
### Cookbook version
N/A

### Chef-client version
N/A

### Platform Details
N/A

### Scenario:
As a consumer I would like to have the JSON output from the profile include a summarization of the her total number of issues discovered or packages out of date (in case of patching). This would allow consumers and users to parse this line and use it in others tools as well as provide a good summarization during a provisioning phase for other provisioners (AWS, Azure, etc)

### Steps to Reproduce:
N/A

### Expected Result:
N/A

### Actual Result:
N/A

**Comment by chris-rock** [comment]
@ffpollock So this need to be in json or should it be a info output in chef client log?

**Comment by chris-rock** [comment]
I close this issue, since we added summary logs for chef logs. Please re-open if other things are required.
