### ISSUE TITLE
Doc is wrong - https://github.com/chef-cookbooks/audit/blob/master/docs/supported_configuration.md

### ISSUE THREAD

**Issue by SteveDelFante** [chef-cookbooks/audit#241]
Report method "Report to Automate via Chef Server"

chef-server-automate does not need the automate url in chef-server.rb since in this scenario we integrated automate with chef server.

```Report to Automate via Chef Server

['audit']['reporter'] = 'chef-server-automate'
['audit']['server'] = 'https://compliance-server.test/api'
['audit']['refresh_token' OR 'token'] = '..'
['audit']['owner'] = 'User/Org'
#
# chef-server.rb:
data_collector['root_url'] = 'https://automate-server.test/data-collector/v0/'
```

### Cookbook version
[Version of the cookbook where you are encountering the issue]

### Chef-client version
[Version of chef-client in your environment]

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by kekaichinose** [comment]
I see this documentation has not been updated. @alexpop do you have any advice on this documentation clean-up? I'm not sure how to update the docs to clear up any misunderstanding that @SteveDelFante was pointing out. Thanks!
