### ISSUE TITLE
json-file reporter saves ruby hash instead of JSON

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef-cookbooks/audit#244]
### Cookbook version

4.0.0

### Chef-client version

13.1.31

### Platform Details

Ubuntu 14.04.5

### Scenario:

Trying to use `json-file` reporter.

### Steps to Reproduce:

```
{
  "audit": {
    "reporter": ["chef-server-automate", "json-file"],
    "insecure": true,
    "profiles": [
      {
        "name": "linux",
        "compliance": "admin/linux"
      }
    ]
  }
}
```

### Expected Result:

The file saved to disk should contain the report in JSON format.

### Actual Result:

The file saved to disk contains the ruby hash of the report.

### Reason:

The bug is in this line.

https://github.com/chef-cookbooks/audit/blob/v4.0.0/libraries/reporters/json_file.rb#L19

It should be changed to the following.

```
      json_file.puts(JSON.generate(report))
```

**Comment by chris-rock** [comment]
@jeremiahsnapp Thank you for reporting this issue! Are you opening a PR to fix this?

**Comment by jeremiahsnapp** [comment]
I just submitted PR #246
