### ISSUE TITLE
Declare audit profile in recipes

### ISSUE THREAD

**Issue by mhedgpeth** [chef-cookbooks/audit#257]
I would like to have a way to have different teams declare what runs in the audit cookbook without bothering each other.

For example, let's say I have three teams: operations, application, and security.
operations wants to run the ops-profile, and logging-profile
application wants to run the application-up-profile
security wants to run cis-profile

Right now there isn't an easy way for these three teams to define that they want to run their profile without affecting the other teams.

This becomes even more problematic when considering that some teams want portions of their infrastructure to run different profiles.

For example:
operations wants to run logging-profile on nodes that have the logging recipe working, but the competitor-logging-profile on nodes that have the competitor's logging recipe running.

So these groups need fine-grained control over _when_ the profile is included.

To solve this problem I suggest adding a library method to the `audit` cookbook:

```ruby
audit_profile 'mycorp/myproduct_profile'
```
The `audit_profile` method would _add_ the given profile to the list, preserving the existing list. That way anyone who wanted to could _add_ to the list but wouldn't harm the list. You would end up getting the aggregate of all your run lists' things.

I'm happy to add a PR for this if you agree with the approach.

**Comment by mhedgpeth** [comment]
@trevorghess updated this comment per our discussion.

**Comment by mhedgpeth** [comment]
Another way of looking at this is that it's an `include_recipe` for profiles

**Comment by jeremymv2** [comment]
@mhedgpeth one way to accomplish this is with some conditional statements based on inspecting the run_list of the node and/or other Ohai based attributes.

You can have a recipe drop off either a full blown Ohai node.json object on the filesystem for inspec to read like [this](https://github.com/jeremymv2/one-profile-to-rule-them-all/blob/master/recipes/default.rb#L16-L20) or just a decomposed json file with only the elements necessary for making decisions (like the node's roles, or run_list). 

Then, in your meta profile, you could make the decisions on which profiles/controls to include like [this](https://github.com/jeremymv2/one-profile-to-rule-them-all/blob/master/test/smoke/profile_meta/controls/example.rb)

**Comment by mhedgpeth** [comment]
Closing this for a different idea that I want to investigate with @jeremymv2
