### ISSUE TITLE
Provide gem_source attribute for fetching any required gems

### ISSUE THREAD

**Issue by smford22** [chef-cookbooks/audit#26]
Right now the source for where we fetch the inspec gem is hardcoded to rubygems.org. Some customers cannot access rubygems.org due to network restrictions. We should provide a `gem_source` attribute to override the source. The chef-vault cookbook provides this override as well...

https://github.com/chef-cookbooks/chef-vault

`default['chef-vault']['gem_source'] = nil`

```
chef_gem 'chef-vault' do # ~FC009
23      source node['chef-vault']['gem_source']
24      version node['chef-vault']['version']
25      clear_sources true unless node['chef-vault']['gem_source'].nil?
26      compile_time true
27    end
```

**Comment by chris-rock** [comment]
aimilar to #8

**Comment by chris-rock** [comment]
InSpec is part of Chef 13. If this is still required, please re-open
