### ISSUE TITLE
Support inspec attributes

### ISSUE THREAD

**Issue by mhedgpeth** [chef-cookbooks/audit#261]
I want to be able to pass in attributes to the inspec profile(s) that are in my list of profiles.

The inspec profile can use [attributes](http://www.anniehedgie.com/inspec-basics-9) and passed in an attributes.yml file. The chef run should be able to define these attributes, per profile, like this:

```json
"audit": {
  "reporter": "chef-server-compliance",
  "inspec_version": "1.29.0",
  "profiles": [
    {
      "name": "linux",
      "compliance": "base/linux",
      "attributes": {
        "role": "mywebserver"
      }
    }
  ]
}
```

The `audit` cookbook will take attributes (if they exist) and pass those to the inspec profile when it runs it.

This enables "one profile to rule them all" pattern that @jeremymv2 proposed, but with a more inspec-native construct.

**Comment by alexpop** [comment]
👍
