### ISSUE TITLE
Warning for format

### ISSUE THREAD

**Issue by xblitz** [chef-cookbooks/audit#277]
Is there any reason why there is a warning about the format? shouldn't be INFO instead?
https://github.com/chef-cookbooks/audit/blob/60dddca559edde41d199e4498ef0bcb2ae0d91f5/files/default/handler/audit_report.rb#L121

**Comment by adamleff** [comment]
Hi @xblitz! Honestly, it should be a `.debug` message. Would you like to put up a PR changing that?

**Comment by xblitz** [comment]
Ok i'll do a PR for it :)
