### ISSUE TITLE
Failing to add nodes: Error:Response from server was : status code 403

### ISSUE THREAD

**Issue by saurabh1611** [chef-cookbooks/audit#307]
### Cookbook version
name 'final_audit'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures final_audit'
depends 'audit'
long_description 'Installs/Configures final_audit'
version '0.1.1'
chef_version '>= 12.1' if respond_to?(:chef_version)

### Chef-client version
Chef: 13.7.16

### Platform Details
RHEL

### Scenario:
I have integrated chef compliance server with chef server. I have logged into my compliance server with chef server credentials. Now when i am trying to add nodes it is showing me an error

![image](https://user-images.githubusercontent.com/32091801/36144943-cabcfae4-10d5-11e8-9a27-88a72264d161.png)

 ### Steps to Reproduce:
I fail to understand what is causing this issue.

### Expected Result:
Node must be added to the compliance server

### Actual Result:
![image](https://user-images.githubusercontent.com/32091801/36145011-faeea32a-10d5-11e8-88a3-4465f0f29424.png)

**Comment by adamleff** [comment]
Hi, @saurabh1611! 

This repo is primarily for supporting and developing the audit cookbook itself. This isn't the best place to get assistance with Chef's commercial products. Instead, please reach out to the Chef Support team at https://www.chef.io/support/

Thanks!
