### ISSUE TITLE
Support ChefClient 14

### ISSUE THREAD

**Issue by jquick** [chef-cookbooks/audit#312]
The Audit cookbook currently is only compatible with ChefClient 13. This has to do with the new handling of inspec version variables. We need to update this codebase to support ChefClient 14 as well as being backwords compatible with 13.

**Comment by wamoore** [comment]
I was able to work around the issue by running the following on all nodes.  You still can't pin the inspec_version afterwards but it won't try to install a version newer than the one installed with chef-client.  It's a workaround anyway.

`knife exec -E "nodes.transform(:all) {|n| n.set['audit']['inspec_version']=nil;n.save() }"`
