### ISSUE TITLE
Remove `.push()` examples from documentation

### ISSUE THREAD

**Issue by jerryaldrichiii** [chef-cookbooks/audit#359]
With the merging of https://github.com/chef-cookbooks/audit/pull/328 using an Array of Hashes for `node['audit']['profiles']` is deprecated. As such we should change all of the documentation to reflect this. This issue is a place to track this work.

Here are some of the sites I found:
  - [X] This repo's README.md (https://github.com/chef-cookbooks/audit/pull/358)
  - [ ] https://docs.chef.io/audit_cookbook.html (doesn't use .push but is still an Array of Hashes)
  - [ ] https://docs.chef.io/integrate_compliance_chef_server.html (doesn't use .push but is still an Array of Hashes)
  - [ ] https://automate.chef.io/docs/data-collection/
  - [ ] https://blog.chef.io/2016/11/09/the-audit-cookbook-a-how-to/

As a side note I feel we point all references on how to use the Audit cookbook to a single location.

@kagarmoe @mjingle thoughts?

**Comment by schisamo** [comment]
@jerryaldrichiii It appears the new hash of hashes format doesn't actually work yet:
https://github.com/chef-cookbooks/audit/issues/339

Shouldn't we get this fixed before attempting to update documentation?

**Comment by alexpop** [comment]
Done, closing. Thank you
