### ISSUE TITLE
Cookbook broken with Chef-15

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/audit#368]
See https://github.com/chef/chef/issues/8557

This mechanism has changed in Chef-15

https://github.com/chef-cookbooks/audit/blob/27df9721690ff9610d9fdee1074b9974dbe3163d/libraries/helper.rb#L17-L25

`node[:chef_guid]` is probably the best public API for that now.

**Comment by lamont-granquist** [comment]
So the code should look more or less like this:

```
   # Returns the node's uuid
   def entity_uuid
    # the Chef::DataCollector::Messages API here is Chef < 15.0 backcompat and can be removed when Chef 14.x is no longer supported
    node[:chef_guid] || defined?(Chef::DataCollector::Messages) && Chef::DataCollector::Messages.node_uuid,
   end
```

The problem is that `node` may or may not be in the context.

It is also more than a bit weird that there appear to be spec tests for `it 'is not sending report when entity_uuid is missing' do` which are clearly not working correctly.

there's also lines in the audit reporter that look like this:

```
./files/default/handler/audit_report.rb:            entity_uuid: run_status.entity_uuid,
./files/default/handler/audit_report.rb:              entity_uuid: run_status.entity_uuid,
```

if that is the Chef::RunStatus object from core chef the it shouldn't have an entity_uuid method and didn't have on in Chef-14 so now I'm super confused.

**Comment by zenspider** [comment]
_SINGLE SPACE INDENT?!?!?_ 😛

Thank you for changing it to `defined?(Chef::DataCollector::Messages)`.

**Comment by lamont-granquist** [comment]
heh starchy copypasta error...

and yes...

**Comment by alexpop** [comment]
@lamont-granquist thanks for assisting with this change.

I looked into it as well.
I don't see a problem with the `is not sending report when entity_uuid is missing` spec test. The `send_report` method is not sending the report if `entity_uuid` is missing, as I noticed in this output:

```
Running handlers:
[2019-05-31T09:01:53+00:00] WARN: Overwriting resource apache. To reference a specific version of apache use the resource() method
[2019-05-31T09:02:02+00:00] ERROR: entity_uuid() or run_id(dd3b05e8-b41f-43fa-a80b-c4d2c9385af7) can't be nil, not sending report to Chef Automate
  - Chef::Handler::AuditReport
```

`run_status.entity_uuid` in audit_report.rb is calling the `entity_uuid` helper method.
I opened PR https://github.com/chef-cookbooks/audit/pull/371 with the fix for this issue.

**Comment by lamont-granquist** [comment]
So what Type of object is run_status?

**Comment by alexpop** [comment]
```ruby
[1] pry(#<Chef::Handler::AuditReport>)> run_status.class
=> Chef::RunStatus
[2] pry(#<Chef::Handler::AuditReport>)> run_status
=> #<Chef::RunStatus:0x0000000003c9e2c8
 @end_time=2019-05-31 18:19:25 +0000,
 @events=
  #<Chef::EventDispatch::Dispatcher:0x0000000003c9e368
   @event_list=[],
   @in_call=false,
...
```
