### ISSUE TITLE
Request: Update the Changelog

### ISSUE THREAD

**Issue by kmf** [chef-cookbooks/audit#377]
Just wanted to know if it could be possible to (maybe automatically) update the Changelog each time the a new release of the Cookbook happens?

**Comment by alexpop** [comment]
Until that's fully automated, I've just merged a CHANGELOG update after releasing version 8.0.0.

**Comment by alexpop** [comment]
@kmf we've got better at updating CHANGELOG with each release.
I'm closing this ticket, thank you for bringing this to our attention.

**Comment by kmf** [comment]
❤️
