### ISSUE TITLE
Use Net::HTTPClientException instead of Net::HTTPServerException

### ISSUE THREAD

**Issue by vsingh-msys** [chef-cookbooks/audit#394]
As we have used `Net::HTTPServerException` and it is deprecated as per the link https://bugs.ruby-lang.org/issues/14688.

https://github.com/chef-cookbooks/audit/blob/584ed7af59d552c5bda1ee77f7ad9f6e06a7f54f/libraries/helper.rb#L47

So need to replace `Net::HTTPServerException` with `Net::HTTPClientException`

**Comment by kekaichinose** [comment]
@vsingh-msys This looks valid. Would you mind submitting a PR for us to get this added? Thanks!

**Comment by vsingh-msys** [comment]
Okay sure @kekaichinose will create a PR.
