### ISSUE TITLE
we should use the latest inspec version by default

### ISSUE THREAD

**Issue by chris-rock** [chef-cookbooks/audit#8]
Currently, the inspec version is hardcoded: 
https://github.com/chef/audit-cookbook/blob/6b18c581bb6103aca79a4a3c28fe5f605545bde3/libraries/profile.rb#L25

We should use `latest` as default and allow users to pin versions if required.

**Comment by sclark007** [comment]
this will be required when the node does not have port 80 open to grab the inspec gem. for this use case i pre-install the cookbooks required gems via using remote_file and chef_gem. 

example: 
  # Grab chef vault gem
  remote_file "#{Chef::Config[:file_cache_path]}/chef-vault-2.6.1.gem" do
    source "#{node['yum-neustar']['repo']}/neustar/gems/gems/chef-vault-2.6.1.gem"
  end.run_action(:create)

  # Install the Chef Vault Gem
  chef_gem 'chef-vault' do # ~FC009
    source "#{Chef::Config[:file_cache_path]}/chef-vault-2.6.1.gem"
    compile_time true
    action :install
  end

**Comment by chris-rock** [comment]
@sclark007 that is a great hint, we should allow this as an option, if no internet access is available. Going forward, we intend to make inspec.gem part of the chef-client, which eliminates the problem.

**Comment by chris-rock** [comment]
@sclark007 your use-case is not yet covered, but we work on a PR for chef-client to include inspec as part of normal chef-client releases. That would eliminate the need to install the gem

**Comment by sclark007** [comment]
thanks.
